version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      retries: 10

  terraform:
    build: ./terraform
    environment:
      - TF_VAR_aws_endpoint=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localstack:4566/_localstack/health"]
      interval: 5s
      retries: 10

  producer:
    build: ./services/producer
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:metrics-topic
    depends_on:
      terraform:
        condition: service_completed_successfully

  consumer:
    build: ./services/consumer
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SQS_QUEUE_URL=http://sqs.us-east-1.localstack.localstack.cloud:4566/000000000000/metrics-queue
    depends_on:
      terraform:
        condition: service_completed_successfully
    ports:
    - "8080:8080"
